"""empty message

Revision ID: 044e9d316ef8
Revises: 
Create Date: 2019-03-27 22:58:17.565957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044e9d316ef8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'playlist',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('last_scan', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.add_column('movie', sa.Column('playlist_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_movie_playlist_name'), 'movie', ['playlist_name'], unique=False)
    op.create_foreign_key(None, 'movie', 'playlist', ['playlist_name'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie', type_='foreignkey')
    op.drop_index(op.f('ix_movie_playlist_name'), table_name='movie')
    op.drop_column('movie', 'playlist_name')
    op.drop_table('playlist')
    # ### end Alembic commands ###
