"""Save file location

Revision ID: 82a544d39514
Revises: 044e9d316ef8
Create Date: 2020-03-26 20:31:33.981680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a544d39514'
down_revision = '044e9d316ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'location')
    # ### end Alembic commands ###
