"""Add clip extension

Revision ID: 20df3809e96b
Revises: 82a544d39514
Create Date: 2020-03-26 23:00:24.162514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20df3809e96b'
down_revision = '82a544d39514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('extension', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'extension')
    # ### end Alembic commands ###
